import { call } from "@decky/api";
import type { Config, FanStatus, SdcardInfo, Tweaks, UpdateInfo, UpdateStatus } from "./types";

export const getConfig = () => call<[], Config>("get_config");
export const setFanMode = (mode: string) => call<[string], Config>("set_fan_mode", mode);
export const saveFanCurve = (name: string, label: string, curve: string) => call<[string, string, string], Config>("save_fan_curve", name, label, curve);
export const deleteFanCurve = (name: string) => call<[string], Config>("delete_fan_curve", name);
export const getFanStatus = () => call<[], FanStatus>("fan_status");
export const setPowerMode = (mode: string) => call<[string], Config>("set_power_mode", mode);
export const setChargeLimit = (pct: number) => call<[number], Config>("set_charge_limit", pct);
export const setLedColor = (hex: string) => call<[string], Config>("set_led_color", hex);
export const setLedMode = (mode: string) => call<[string], Config>("set_led_mode", mode);
export const setDownloadInhibitMode = (mode: string) => call<[string], Config>("set_download_inhibit_mode", mode);
export const setLavdMode = (mode: string) => call<[string], Config>("set_lavd_mode", mode);
export const saveTweaks = (data: Tweaks) => call<[Tweaks], Config>("save_tweaks", data);
export const detectSdcard = () => call<[], SdcardInfo>("detect_sdcard");
export const formatSdcard = (label: string) => call<[string], SdcardInfo>("format_sdcard", label);
export const checkUpdates = () => call<[], UpdateInfo[]>("check_updates");
export const startUpdate = () => call<[], UpdateStatus>("start_update");
export const updateStatus = () => call<[], UpdateStatus>("update_status");
